name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_CLIENT_ID }}
          VITE_AZURE_TENANT_ID: ${{ secrets.VITE_AZURE_TENANT_ID }}
          VITE_AZURE_COSMOS_CONNECTION_STRING: ${{ secrets.VITE_AZURE_COSMOS_CONNECTION_STRING }}
          VITE_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.VITE_AZURE_STORAGE_CONNECTION_STRING }}
          VITE_AZURE_STORAGE_ACCOUNT: ${{ secrets.VITE_AZURE_STORAGE_ACCOUNT }}
          VITE_AZURE_VISION_API_KEY: ${{ secrets.VITE_AZURE_VISION_API_KEY }}
          VITE_AZURE_VISION_ENDPOINT: ${{ secrets.VITE_AZURE_VISION_ENDPOINT }}
          VITE_JWT_SECRET: ${{ secrets.VITE_JWT_SECRET }}
          VITE_GOOGLE_VISION_API_KEY: ${{ secrets.VITE_GOOGLE_VISION_API_KEY }}

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_DESERT_0764E6B00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ".output/public"
        env:
          VITE_AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_CLIENT_ID }}
          VITE_AZURE_TENANT_ID: ${{ secrets.VITE_AZURE_TENANT_ID }}
          VITE_AZURE_COSMOS_CONNECTION_STRING: ${{ secrets.VITE_AZURE_COSMOS_CONNECTION_STRING }}
          VITE_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.VITE_AZURE_STORAGE_CONNECTION_STRING }}
          VITE_AZURE_STORAGE_ACCOUNT: ${{ secrets.VITE_AZURE_STORAGE_ACCOUNT }}
          VITE_AZURE_VISION_API_KEY: ${{ secrets.VITE_AZURE_VISION_API_KEY }}
          VITE_AZURE_VISION_ENDPOINT: ${{ secrets.VITE_AZURE_VISION_ENDPOINT }}
          VITE_JWT_SECRET: ${{ secrets.VITE_JWT_SECRET }}
          VITE_GOOGLE_VISION_API_KEY: ${{ secrets.VITE_GOOGLE_VISION_API_KEY }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_DESERT_0764E6B00 }}
          action: "close"
          app_location: "/"

